// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mfreeman451/serviceradar/pkg/sweeper (interfaces: Sweeper,ResultProcessor,Store,Reporter,SweepService)
//
// Generated by this command:
//
//	mockgen -destination=mock_sweeper.go -package=sweeper github.com/mfreeman451/serviceradar/pkg/sweeper Sweeper,ResultProcessor,Store,Reporter,SweepService
//

// Package sweeper is a generated GoMock package.
package sweeper

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/mfreeman451/serviceradar/pkg/models"
	gomock "go.uber.org/mock/gomock"
)

// MockSweeper is a mock of Sweeper interface.
type MockSweeper struct {
	ctrl     *gomock.Controller
	recorder *MockSweeperMockRecorder
	isgomock struct{}
}

// MockSweeperMockRecorder is the mock recorder for MockSweeper.
type MockSweeperMockRecorder struct {
	mock *MockSweeper
}

// NewMockSweeper creates a new mock instance.
func NewMockSweeper(ctrl *gomock.Controller) *MockSweeper {
	mock := &MockSweeper{ctrl: ctrl}
	mock.recorder = &MockSweeperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSweeper) EXPECT() *MockSweeperMockRecorder {
	return m.recorder
}

// GetConfig mocks base method.
func (m *MockSweeper) GetConfig() models.Config {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig")
	ret0, _ := ret[0].(models.Config)
	return ret0
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockSweeperMockRecorder) GetConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockSweeper)(nil).GetConfig))
}

// GetResults mocks base method.
func (m *MockSweeper) GetResults(arg0 context.Context, arg1 *models.ResultFilter) ([]models.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResults", arg0, arg1)
	ret0, _ := ret[0].([]models.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResults indicates an expected call of GetResults.
func (mr *MockSweeperMockRecorder) GetResults(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResults", reflect.TypeOf((*MockSweeper)(nil).GetResults), arg0, arg1)
}

// Start mocks base method.
func (m *MockSweeper) Start(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockSweeperMockRecorder) Start(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockSweeper)(nil).Start), arg0)
}

// Stop mocks base method.
func (m *MockSweeper) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockSweeperMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockSweeper)(nil).Stop))
}

// UpdateConfig mocks base method.
func (m *MockSweeper) UpdateConfig(arg0 models.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConfig", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateConfig indicates an expected call of UpdateConfig.
func (mr *MockSweeperMockRecorder) UpdateConfig(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfig", reflect.TypeOf((*MockSweeper)(nil).UpdateConfig), arg0)
}

// MockResultProcessor is a mock of ResultProcessor interface.
type MockResultProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockResultProcessorMockRecorder
	isgomock struct{}
}

// MockResultProcessorMockRecorder is the mock recorder for MockResultProcessor.
type MockResultProcessorMockRecorder struct {
	mock *MockResultProcessor
}

// NewMockResultProcessor creates a new mock instance.
func NewMockResultProcessor(ctrl *gomock.Controller) *MockResultProcessor {
	mock := &MockResultProcessor{ctrl: ctrl}
	mock.recorder = &MockResultProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResultProcessor) EXPECT() *MockResultProcessorMockRecorder {
	return m.recorder
}

// GetSummary mocks base method.
func (m *MockResultProcessor) GetSummary(ctx context.Context) (*models.SweepSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSummary", ctx)
	ret0, _ := ret[0].(*models.SweepSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSummary indicates an expected call of GetSummary.
func (mr *MockResultProcessorMockRecorder) GetSummary(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSummary", reflect.TypeOf((*MockResultProcessor)(nil).GetSummary), ctx)
}

// Process mocks base method.
func (m *MockResultProcessor) Process(result *models.Result) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", result)
	ret0, _ := ret[0].(error)
	return ret0
}

// Process indicates an expected call of Process.
func (mr *MockResultProcessorMockRecorder) Process(result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockResultProcessor)(nil).Process), result)
}

// Reset mocks base method.
func (m *MockResultProcessor) Reset() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Reset")
}

// Reset indicates an expected call of Reset.
func (mr *MockResultProcessorMockRecorder) Reset() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockResultProcessor)(nil).Reset))
}

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// GetResults mocks base method.
func (m *MockStore) GetResults(arg0 context.Context, arg1 *models.ResultFilter) ([]models.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResults", arg0, arg1)
	ret0, _ := ret[0].([]models.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResults indicates an expected call of GetResults.
func (mr *MockStoreMockRecorder) GetResults(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResults", reflect.TypeOf((*MockStore)(nil).GetResults), arg0, arg1)
}

// GetSweepSummary mocks base method.
func (m *MockStore) GetSweepSummary(arg0 context.Context) (*models.SweepSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSweepSummary", arg0)
	ret0, _ := ret[0].(*models.SweepSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSweepSummary indicates an expected call of GetSweepSummary.
func (mr *MockStoreMockRecorder) GetSweepSummary(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSweepSummary", reflect.TypeOf((*MockStore)(nil).GetSweepSummary), arg0)
}

// PruneResults mocks base method.
func (m *MockStore) PruneResults(arg0 context.Context, arg1 time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PruneResults", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PruneResults indicates an expected call of PruneResults.
func (mr *MockStoreMockRecorder) PruneResults(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PruneResults", reflect.TypeOf((*MockStore)(nil).PruneResults), arg0, arg1)
}

// SaveResult mocks base method.
func (m *MockStore) SaveResult(arg0 context.Context, arg1 *models.Result) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveResult", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveResult indicates an expected call of SaveResult.
func (mr *MockStoreMockRecorder) SaveResult(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveResult", reflect.TypeOf((*MockStore)(nil).SaveResult), arg0, arg1)
}

// MockReporter is a mock of Reporter interface.
type MockReporter struct {
	ctrl     *gomock.Controller
	recorder *MockReporterMockRecorder
	isgomock struct{}
}

// MockReporterMockRecorder is the mock recorder for MockReporter.
type MockReporterMockRecorder struct {
	mock *MockReporter
}

// NewMockReporter creates a new mock instance.
func NewMockReporter(ctrl *gomock.Controller) *MockReporter {
	mock := &MockReporter{ctrl: ctrl}
	mock.recorder = &MockReporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReporter) EXPECT() *MockReporterMockRecorder {
	return m.recorder
}

// Report mocks base method.
func (m *MockReporter) Report(arg0 context.Context, arg1 *models.SweepSummary) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Report", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Report indicates an expected call of Report.
func (mr *MockReporterMockRecorder) Report(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Report", reflect.TypeOf((*MockReporter)(nil).Report), arg0, arg1)
}

// MockSweepService is a mock of SweepService interface.
type MockSweepService struct {
	ctrl     *gomock.Controller
	recorder *MockSweepServiceMockRecorder
	isgomock struct{}
}

// MockSweepServiceMockRecorder is the mock recorder for MockSweepService.
type MockSweepServiceMockRecorder struct {
	mock *MockSweepService
}

// NewMockSweepService creates a new mock instance.
func NewMockSweepService(ctrl *gomock.Controller) *MockSweepService {
	mock := &MockSweepService{ctrl: ctrl}
	mock.recorder = &MockSweepServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSweepService) EXPECT() *MockSweepServiceMockRecorder {
	return m.recorder
}

// GetStatus mocks base method.
func (m *MockSweepService) GetStatus(arg0 context.Context) (*models.SweepSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", arg0)
	ret0, _ := ret[0].(*models.SweepSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockSweepServiceMockRecorder) GetStatus(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockSweepService)(nil).GetStatus), arg0)
}

// Start mocks base method.
func (m *MockSweepService) Start(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockSweepServiceMockRecorder) Start(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockSweepService)(nil).Start), arg0)
}

// Stop mocks base method.
func (m *MockSweepService) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockSweepServiceMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockSweepService)(nil).Stop))
}

// UpdateConfig mocks base method.
func (m *MockSweepService) UpdateConfig(arg0 models.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConfig", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateConfig indicates an expected call of UpdateConfig.
func (mr *MockSweepServiceMockRecorder) UpdateConfig(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfig", reflect.TypeOf((*MockSweepService)(nil).UpdateConfig), arg0)
}
