// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mfreeman451/serviceradar/pkg/cloud/api (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=mock_api_server.go -package=api github.com/mfreeman451/serviceradar/pkg/cloud/api Service
//

// Package api is a generated GoMock package.
package api

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// SetKnownPollers mocks base method.
func (m *MockService) SetKnownPollers(knownPollers []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetKnownPollers", knownPollers)
}

// SetKnownPollers indicates an expected call of SetKnownPollers.
func (mr *MockServiceMockRecorder) SetKnownPollers(knownPollers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetKnownPollers", reflect.TypeOf((*MockService)(nil).SetKnownPollers), knownPollers)
}

// SetNodeHistoryHandler mocks base method.
func (m *MockService) SetNodeHistoryHandler(handler func(string) ([]NodeHistoryPoint, error)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetNodeHistoryHandler", handler)
}

// SetNodeHistoryHandler indicates an expected call of SetNodeHistoryHandler.
func (mr *MockServiceMockRecorder) SetNodeHistoryHandler(handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNodeHistoryHandler", reflect.TypeOf((*MockService)(nil).SetNodeHistoryHandler), handler)
}

// Start mocks base method.
func (m *MockService) Start(addr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", addr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockServiceMockRecorder) Start(addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockService)(nil).Start), addr)
}

// UpdateNodeStatus mocks base method.
func (m *MockService) UpdateNodeStatus(nodeID string, status *NodeStatus) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateNodeStatus", nodeID, status)
}

// UpdateNodeStatus indicates an expected call of UpdateNodeStatus.
func (mr *MockServiceMockRecorder) UpdateNodeStatus(nodeID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNodeStatus", reflect.TypeOf((*MockService)(nil).UpdateNodeStatus), nodeID, status)
}
